### PR TITLE
Sort map keys so output is deterministic

### PR DESCRIPTION
**Pull request by icholy**
Since map iteration order is randomised, the tests randomly pass/fail. This change sorts the map keys before encoding to keep the output deterministic. Now the test always pass.

### CODE REVIEW

**Comment by kolo** [comment]
Thank you for contribution. I don't like an idea of adding unnecessary operation to the encoding just to make the tests passing. I think this should be solved on the test level.

**Comment by icholy** [comment]
@kolo are you opposed because of the performance overhead?

**Comment by kolo** [comment]
@icholy mostly, but it also doesn't look good from my point of view.

**Comment by icholy** [comment]
My original plan was to have a unexported flag to only enable this behavior during tests and I decided against that for the following reasons:

* Having a consistent output seems cleaner from a user's perspective.
* I think that the performance overhead is negligible.
* Go 1.12 [changed](https://golang.org/doc/go1.12#fmt) the `fmt.Printf` function to sort map keys for the exact same reason.

I don't have a strong preference either way. I'll add the flag if you'd prefer that approach.

**Comment by kolo** [comment]
I think having a flag is a good compromise.

**Comment by icholy** [comment]
@kolo since these are only running during tests, I've switched to using `sort.Slice` to shorten up the code.

**Pull request merged**
