### PR TITLE
Update

### PR DESCRIPTION
**Pull request by giautm**

### CODE REVIEW

**Comment by kolo** [comment]
Hi, thank you for the PR. I'm sorry, but I can't merge it as it is as it includes multiple changes. I left the project without attention for a long time, I need to catch up, it will take some time.

**Comment by giautm** [comment]
@kolo : Hi, I just use the fork of this project from @renier , this PR just make the changes to officially. So you can take some time to preview this. Tks for your project. <3

**Comment by kolo** [comment]
I'm working through it. Some of the changes have been merged already. See #49, #51. Most of the changes lack tests, I'm adding tests before merging them. This is the reason behind creation of separate PR's.

**Comment by kolo** [comment]
I decided not merge rest of the changes as it is hard to go through them. The project goes into minimal maintenance mode, thank you for contribution.

**Pull request closed without merging**
